### ISSUE TITLE
Error if the Port 80 is already in use

### ISSUE THREAD

**Issue by ostelaymetaule** [cynicaloptimist/improved-initiative#13]
If the localhost:80 already have some other web application attached to (for example a web service running on IIS) the "node server.js" command will not run the app and gives following error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (C:\dev\GitHub\improved-initiative\server.js:111:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Quick fix for anyone confronting this problem: 
find in the server.js file 
`var port = process.env.PORT || 80; `
and change it for example to 
`var port = process.env.PORT || 88;`
now you will find the improved-initiative on `http://localhost:88/`

**Comment by shakefu** [comment]
You can also do `PORT=88 node server.js` and it should pick it up.

**Comment by cynicaloptimist** [comment]
Thanks for the workaround instructions, ostelay. I'm closing this issue, though, as I'm not convinced it's a bug.
