### ISSUE TITLE
npm start fails with unhandled error

### ISSUE THREAD

**Issue by AJAnderson** [cynicaloptimist/improved-initiative#254]
Followed the instructions in the readme but failed at npm start as below, have appended logs as well.
[2018-06-30T00_49_30_804Z-debug.log](https://github.com/cynicaloptimist/improved-initiative/files/2151269/2018-06-30T00_49_30_804Z-debug.log)

C:\Users\USER\Desktop\Alex\DnD\improved-initiative-master>npm start

> improved-initiative@1.6.4 start C:\Users\USER\Desktop\Alex\DnD\improved-initiative-master
> node server/server.js

No connection string found.
Keen configuration variables not set.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1465:7)
    at Object.default_1 [as default] (C:\Users\USER\Desktop\Alex\DnD\improved-initiative-master\server\launchserver.js:5:23)
    at Object.<anonymous> (C:\Users\USER\Desktop\Alex\DnD\improved-initiative-master\server\server.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! improved-initiative@1.6.4 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the improved-initiative@1.6.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2018-06-30T00_49_30_804Z-debug.log

C:\Users\USER\Desktop\Alex\DnD\improved-initiative-master>

**Comment by AJAnderson** [comment]
I figured out it was because something was using the 80 port already.

**Comment by AJAnderson** [comment]
how can one pass arguments on startup? I'm not too familiar with JS stuff.

**Comment by cynicaloptimist** [comment]
What arguments are you trying to pass, and what are you trying to pass them to?

**Comment by AJAnderson** [comment]
I assumed the various switches in the readme i.e. PORT, NODE_ENV etc could be passed as arguments. I can't find any config files where those parameters appear to be set (sorry to be a bother).

I did find launchServer.js which is how I figured out the port was wrong, but it doesn't have any of the other parameters mentioned in the readme defined there. Could you know where the best place is to input those parameters?

**Comment by cynicaloptimist** [comment]
Sure thing, sorry this isn't detailed more in the readme at the moment. There are a handful of different ways to set environment variables for a node app depending on where you're running; I do it with a launch.json file that VS Code uses for local debugging. This file isn't checked in because it contains some private connection strings.

If you're running in powershell, this [StackOverflow](https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows) post should get you in the right direction. Hope that helps!

**Comment by AJAnderson** [comment]
The answers in that thread helped, thank you!
